### ISSUE TITLE
Handling quiet mode

### ISSUE THREAD

**Issue by sudo-nice** [muennich/iptckwed#2]
How do you thing, isn't better to swap
 `Exiv2::LogMsg::setLevel(Exiv2::LogMsg::error);` to
 `Exiv2::LogMsg::setLevel(Exiv2::LogMsg::mute);` with '-q' option, rather than trying to catch `Exiv2::AnyError`?
In my case, '-q' is not working currently.

**Comment by muennich** [comment]
Can you please post the messages that get printed while using `-q`?

**Comment by sudo-nice** [comment]
Some exiv2 errors, like this: "Error: Directory NikonPreview with 8224 entries considered invalid; not read."

**Comment by sudo-nice** [comment]
Here is an example image: http://i.imgur.com/3M0y7nj.jpg

**Comment by xyb3rt** [comment]
I've changed the log level to `Exiv2::LogMsg::mute`, but we still have to catch errors.

**Comment by sudo-nice** [comment]
Ok, thank you!
